/*---------------------------------------------------------------------------------

    snesgame2 - Genesis Invaders (PVSnesLib)

    Move the SNES sprite with the D-pad, fire with A/B. Sega Genesis consoles
    drop in from the top of the screen; shoot one and it flashes then vanishes.
    Press Y to set off a screen-clearing bomb.

---------------------------------------------------------------------------------*/
#include <snes.h>
#include <string.h>             // strlen/memset, used to blank the credits crawl text

#include "sprites.inc"          // player: sprites_til/_tilend, sprites_pal/_palend
#include "enemy.inc"            // enemy:  enemy_til/_tilend,   enemy_pal/_palend
#include "bullet.inc"           // bullet: bullet_til/_tilend,  bullet_pal/_palend
#include "powerup.inc"          // bomb pickup: powerup_til/_tilend, powerup_pal/_palend
#include "tac2.inc"             // tough enemy: tac2_til/_tilend,   tac2_pal/_palend
#include "deepspace.inc"        // far layer:   deepspace_til/_map/_pal (+ _end)
#include "nearstars.inc"        // near layer:  nearstars_til/_map/_pal (+ _end)

#include "res/soundbank.h"      // soundbank module ids (generated by smconv)

// Font tiles + palette, linked from data.asm
extern char tilfont, palfont;

// Backdrop gradient HDMA tables (gfx4snes -n), linked from data.asm
extern char hdmaGradskygradList, hdmaGradskygrad_flipList;

// Sound effect bank (generated by smconv into res/soundbank.asm)
extern char SOUNDBANK__;

// Gun-fire BRR sample (linked from data.asm). brrsamples holds the registered
// sound-table entry that spcSetSoundEntry fills in.
extern char gunshot_brr, gunshot_brrend;
brrsamples gunSound;

// --- Sound effects -------------------------------------------------------------
// The bank holds 5 sampled instruments (loaded as effects 0..4). We reuse them
// for game events, leaning on pitch/volume to give each its own character.
// spcEffect(pitch, sfxIndex, volpan): pitch 1=4kHz..8=32kHz, volpan = vol*16+pan.
#define SFX_TADA      0
#define SFX_STRINGS   1
#define SFX_PIANO     2
#define SFX_MARIMBA   3
#define SFX_COWBELL   4
#define NUM_SFX       5

#define PAN_CENTER    8

// Gun fire: a real noise-burst gunshot BRR sample (see tools/make_gunshot.js),
// not a pitched instrument -- spcPlaySound(0) replays the last-loaded sound.
#define sfxFire()     spcPlaySound(0)
// Enemy hit: a clean high marimba "ding" to confirm the kill.
#define sfxEnemyHit() spcEffect(8,  SFX_MARIMBA, 12 * 16 + PAN_CENTER)
// Tough enemy chipped but not killed: a duller, lower marimba "thunk".
#define sfxTankHit()  spcEffect(4,  SFX_MARIMBA, 10 * 16 + PAN_CENTER)
// Player collision: a low, hard metallic cowbell whack at max volume -- the
// percussive sample gives it a sharp attack (punch) and the low pitch makes it
// harsh rather than the softer piano thud it used to be.
#define sfxCollide()  spcEffect(2,  SFX_COWBELL, 15 * 16 + PAN_CENTER)
// Game over: deep, slow strings = mournful.
#define sfxGameOver() spcEffect(1,  SFX_STRINGS, 15 * 16 + PAN_CENTER)
// Bomb power-up collected: a bright, high "tada" flourish.
#define sfxPowerup()  spcEffect(8,  SFX_TADA, 14 * 16 + PAN_CENTER)

// --- Title-screen fanfare ------------------------------------------------------
// A short, hard-driving riff played on the percussive cowbell sample (sharp
// attack = punch) at full volume while the splash screen is up. spcEffect pitch
// indices map to playback rates of 4*index kHz, so the indices 4:6:8 sound that
// same frequency ratio -- root, fifth and octave. The riff leans on the low root
// (4) on the beat with high stabs (8) for an aggressive, galloping feel.
#define JINGLE_STEP_FRAMES 6                // frames each note is held (~10 notes/sec, driving)
const unsigned char jingleNotes[] = {
    8, 4, 8, 6,  4, 8, 6, 4    // fast, accented arpeggio -- punchy low root on every beat
};
#define JINGLE_LEN (sizeof(jingleNotes))

#define SCREEN_W      256
#define ENEMY_SIZE    21        // art is 2/3 of the 32x32 cell (rest transparent)
#define PLAYER_SIZE   21
#define BULLET_SIZE   8
#define MAX_ENEMIES   12        // hard cap: sizes the enemy arrays + reserved OAM slots
#define START_ENEMIES 3         // active enemies on screen at score 0
#define ENEMIES_PER_LEVEL 1000  // +1 active enemy per this many points; slow ramp to MAX_ENEMIES
                                // (SCORE_PER_KILL is 100, so ~10 kills per extra enemy)
#define NUM_BULLETS   4
#define BULLET_SPEED  4
#define FLASH_FRAMES  12        // how long a hit console blinks before it disappears
#define OFFSCREEN_Y   224       // park spot for hidden sprites. Must clear the 224-line
                                // screen (y >= 224) AND keep a 32-tall sprite from wrapping:
                                // SNES sprite Y is 8-bit, so y+31 must stay <= 255 or the
                                // sprite's lower rows reappear at the top of the screen
                                // (the upper-left "ghost"). y = 224 is the only value that
                                // satisfies both for our 32x32 player/enemy sprites.
#define PLAYFIELD_TOP 24        // top 3 tile-rows (y 0..23) are the stats bar
#define PLAYFIELD_BOTTOM (224 - PLAYFIELD_TOP)  // 200 -- mirror of PLAYFIELD_TOP: bottom
                                 // 3 tile-rows, reserved for the stats bar in upside-down mode
#define HUD_ROW_TOP    1        // stats-bar text row in normal play (topmost fully-visible row)
#define HUD_ROW_BOTTOM 26       // stats-bar text row in upside-down play (bottommost fully-visible row)
#define SCORE_PER_KILL 100
#define TANK_SCORE    300       // a 3-hit TAC-2 joystick is worth triple a console
#define WIN_SCORE     5000	    // score that triggers the "game completed" screen;
                                 // tune this down (e.g. 200) to reach it quickly for debugging
#define TANK_HEALTH   3         // hits to destroy the tough enemy
#define TANK_CHANCE   5         // ~1 in this many spawns is a tough enemy
#define HURT_FRAMES   8         // brief flicker after a non-lethal hit
// Enemy kinds (per-slot): a normal Genesis console, or the tough TAC-2 joystick.
#define ENEMY_NORMAL  0
#define ENEMY_TANK    1
#define START_LIVES   5
#define START_BOMBS   1
#define MAX_BOMBS     9         // inventory is shown as a single HUD digit
#define POWERUP_SIZE  16        // bomb-pickup hit-box. The bomb art is drawn at half
                                // size (16x16) in the top-left of its 32x32 sprite cell,
                                // so the catch box is the upper-left 16x16 of the cell.
#define POWERUP_SPEED 1         // pixels/frame the dropped bomb falls
#define PLAYER_FLASH_FRAMES 60  // ~1s of blink + invulnerability after a hit
// SNES BG scroll registers only hold whole pixels, so any slow crawl is really a
// "move 1px every few frames" stair-step -- a fixed "wait N frames" step makes
// that stair-step as even as it can be, but a sub-pixel accumulator (mirroring
// enemySpeed/enemyFrac's descent) allows non-integer average speeds too, so the
// step spacing can alternate (e.g. 5,5,6,5,5,6 frames) instead of being locked
// to a single whole-number gap -- marginally smoother for the same overall pace.
#define CREDITS_SCROLL_SPEED 51        // 1/256ths of a px per frame (~1px every 5 frames)
#define CREDITS_START_DELAY_FRAMES 90  // blank pause after the screen clears, before text appears
// spcPlaySound() doesn't send the gunshot sample in one go: it only flags a
// transfer, and spcProcess() then feeds the SPC700 a chunk per frame over the
// ~40-50 frames the ~3KB sample takes to stream across the four APU I/O ports.
// pvsneslib gives no way to ask whether that stream has finished, and starting
// a module load mid-stream talks over the very same ports the stream handshake
// uses: the sound driver desyncs, and since every pvsneslib wait on those ports
// spins with no timeout, the game hangs -- sometimes at the transition itself,
// sometimes minutes into the next round when the corrupted driver finally
// chokes on a command. So before any spcLoad we keep calling spcProcess for
// comfortably longer than a full gunshot playback, guaranteeing the ports are
// quiet. The winning kill is usually scored by a just-fired shot, so a stream
// being mid-flight when the win sequence starts is the common case, not the
// rare one.
#define STREAM_SETTLE_FRAMES 60        // ~1s: > the ~50 frames a full gunshot stream needs
#define STREAM_REGION_PAGES  16        // SPC RAM reserved for streamed BRR sfx (256b pages)
#define WIN_PAUSE_FRAMES     60        // freeze right after the winning kill; kept >=
                                       // STREAM_SETTLE_FRAMES so it doubles as the settle
                                       // window before the win music is loaded
#define WIN_CONGRATS_FRAMES 300        // ~5s (60fps) the "CONGRATULATIONS" banner stays up
#define WIN_PHASE_PAUSE     0          // frozen field, about to show the banner
#define WIN_PHASE_CONGRATS  1          // "CONGRATULATIONS" banner is up
#define WIN_PHASE_CREDITS   2          // screen cleared, credits crawling
// MOD_SUMMERGAMES has no baked-in loop point (see tools/make_music_it.py --
// its .it pattern data has no jump/break effect), so the game manually
// restarts it once its known length has played out: 256 rows at
// speed=3/tempo=160 (2.5*3/160 = 0.046875s/row) = 12s = 720 frames at 60fps.
#define MUSIC_LOOP_FRAMES 720

// Each gfx4snes 32x32 sprite is a 64-tile (0x400-word) block; lay them end to end.
#define VRAM_PLAYER   0x0000
#define VRAM_ENEMY    0x0400
#define VRAM_BULLET   0x0800
#define VRAM_POWERUP  0x0C00    // free VRAM gap (0x0C00..0x0FFF), below the near-star tiles
// The TAC-2 enemy block sits in the free 0x400-word gap between the near-star
// tiles (end by 0x1BFF) and BG0 gfx (0x2000) -- still inside the sprite name range.
#define VRAM_TANK     0x1C00
#define GFX_PLAYER    0x0000
#define GFX_ENEMY     0x0040    // VRAM_ENEMY   / 16
#define GFX_BULLET    0x0080    // VRAM_BULLET  / 16
#define GFX_POWERUP   0x00C0    // VRAM_POWERUP / 16
#define GFX_TANK      0x01C0    // VRAM_TANK    / 16

// Sprite palettes live at CGRAM 128, 16 entries apart.
#define PAL_ENEMY_CG   (128 + 1 * 16)
#define PAL_BULLET_CG  (128 + 2 * 16)
#define PAL_POWERUP_CG (128 + 3 * 16)
#define PAL_TANK_CG    (128 + 4 * 16)
#define PAL_TANK_SP    4        // sprite palette number for the TAC-2 (CGRAM 192..207)

// OAM sprite ids are the sprite index * 4.
#define OAM_PLAYER    0
#define OAM_ENEMY(i)  (((i) + 1) * 4)
#define OAM_BULLET(j) (((j) + 1 + MAX_ENEMIES) * 4)
#define OAM_POWERUP   ((1 + MAX_ENEMIES + NUM_BULLETS) * 4)

// --- Parallax space backdrop ---------------------------------------------------
// Two static tilemaps that only ever get scrolled (one register write each per
// frame, no sprite or scanline cost), at different speeds for depth:
//   BG1 (4bpp) near stars: brighter, coloured stars, a few twinkling sparkles.
//   BG2 (2bpp) deep space: faint planets, a ringed gas giant and its moon, a
//              comet, a nebula, a distant galaxy and dim far stars -- crawling
//              at a quarter of the near layer's speed, so it reads as far away.
// Mode 1 always draws BG1 over BG2, so near stars correctly pass in front of
// the planets. Both maps are 32x64 tiles (256x512px) and wrap, so each layer
// loops seamlessly every 512px. Art: tools/make_space_bmp.py.
// Char bases must be 0x1000-word aligned, map bases 0x400-aligned.
#define NEAR_GFX_VRAM      0x1000   // 4bpp tiles; must end below the TAC-2 at 0x1C00
#define DEEP_GFX_VRAM      0x4000   // 2bpp tiles (0x4000..0x5FFF available)
#define DEEP_MAP_VRAM      0x6000   // 32x64 map = 0x800 words
#define NEAR_MAP_VRAM      0x7000
#define DEEP_MAP_FLIP_VRAM 0x7800   // mirrored copy, for the upside-down world
#define DEEP_MAP_ROWS      64
#define DEEP_CG            8        // deep sub-palettes 2..7 -> CGRAM 8..31 (font uses 0..7)
#define NEAR_CG            32       // near-star sub-palette 2 -> CGRAM 32..47
#define NEAR_SCROLL_PX     1        // near stars drift 1px per frame...
#define DEEP_SCROLL_SPEED  64       // ...deep space 64/256 = 1/4px per frame
// Twinkle: three groups of sparkle stars, each with a core and an arm colour
// (CGRAM 42..47), cycled through an 8-step pulse with the groups out of phase.
#define TWINKLE_CG         (NEAR_CG + 10)
#define TWINKLE_STEP_FRAMES 6
// Backdrop: an HDMA gradient rewrites CGRAM 0 every scanline (dark at the top,
// the familiar navy further down). This is just the colour before HDMA starts.
#define SKY_COLOR          RGB5(0, 1, 5)
#define SKY_HDMA_CHANNEL   HDMA_CHANNEL6
#define HUD_MASK_HDMA_CHANNEL HDMA_CHANNEL5  // stats-bar sprite mask (setScreenOrientation)

// --- Enemy state ---
// The arrays enemies.asm walks are all 16-bit, so it can index every one of
// them with the same register (X = enemy * 2).
short enemyX[MAX_ENEMIES];
short enemyY[MAX_ENEMIES];      // logical y (pixels); negative = sliding in from the top
short enemySpeed[MAX_ENEMIES];           // descent speed in 1/256ths of a pixel per frame
unsigned short enemyFrac[MAX_ENEMIES];   // sub-pixel accumulator for slow movement (0..255)
unsigned short enemyFlash[MAX_ENEMIES];  // >0 while playing the death/blink animation
unsigned short enemyHurt[MAX_ENEMIES];   // >0 = brief flicker after a non-lethal hit
unsigned char enemyType[MAX_ENEMIES];    // ENEMY_NORMAL (console) or ENEMY_TANK (joystick)
unsigned char enemyHealth[MAX_ENEMIES];  // hits remaining before destruction
unsigned char activeEnemies = START_ENEMIES;  // how many enemies are live right now;
                                              // grows with score up to MAX_ENEMIES
unsigned short nextEnemyScore = ENEMIES_PER_LEVEL;  // score at which the next enemy joins
                                                    // (a running threshold -- avoids a
                                                    // per-frame divide)

// --- Upside-down world ---
// Toggled by pressing START during the win sequence (see the gameWon block):
// mirrors the whole game vertically -- ship near the top, enemies climbing
// from the bottom, stats bar flipped to the bottom row too. Persists across
// resetGame() calls (game-over and win-skip alike) until toggled again.
unsigned char upsideDown = 0;
unsigned char hudRow = HUD_ROW_TOP;      // stats-bar text row; flips with upsideDown

// --- Score ---
unsigned short score = 0;
unsigned short lastScore = 0xFFFF;       // force first HUD draw
char scoreStr[8];

// --- Player lives / state ---
unsigned char lives = START_LIVES;
unsigned char lastLives = 0xFF;          // force first HUD draw
unsigned char playerFlash = 0;           // >0 = recently hit: blinking + invulnerable
unsigned char gameOver = 0;
char livesStr[4];

// --- Game-complete state ---
// Reusing BG0 (the text/HUD layer) for the credits crawl: it's otherwise idle
// once play is frozen, and hardware-scrolling it costs nothing per frame, just
// like the space backdrop's scroll trick.
unsigned char gameWon = 0;               // true once WIN_SCORE is reached
unsigned char winPhase = WIN_PHASE_PAUSE;  // where we are in the win sequence
unsigned short winTimer = 0;              // counts down frames within the current phase
unsigned short creditsScroll = 0;        // BG0 vertical scroll offset for the crawl
unsigned char creditsFrac = 0;           // sub-pixel accumulator for CREDITS_SCROLL_SPEED
unsigned char creditsPause = 0;          // counts down CREDITS_START_DELAY_FRAMES before
                                          // the crawl text is drawn and starts moving
unsigned short musicFrame = 0;           // frames since MOD_SUMMERGAMES last (re)started

// --- Bomb inventory ---
unsigned char bombs = START_BOMBS;
unsigned char lastBombs = 0xFF;          // force first HUD draw
char bombStr[4];

// --- Bullet state ---
short bulletX[NUM_BULLETS];
short bulletY[NUM_BULLETS];
unsigned char bulletActive[NUM_BULLETS];

// --- Bomb power-up drop ---
// At most one bomb pickup exists at a time: it falls straight down from a
// destroyed console, and catching it adds a bomb to the inventory.
short powerupX, powerupY;
unsigned char powerupActive = 0;
unsigned char killsSinceDrop = 0;        // kills counted toward the next drop
unsigned char dropThreshold  = 10;       // drop after ~this many kills (jittered)

// --- Parallax space backdrop state ---
unsigned short nearScroll = 0;           // BG1 vertical scroll offset
unsigned short deepScroll = 0;           // BG2 vertical scroll offset
unsigned short deepFrac = 0;             // sub-pixel accumulator for DEEP_SCROLL_SPEED
unsigned short twinkleTimer = 0;         // frames since the last twinkle step
unsigned short twinkleOfs = 0;           // byte offset of the current twinkleFrames row
unsigned short flipRow[32];              // one map row, staged for the mirrored deep map

// Twinkle pulse: 8 phases of {core, arm} -- the core dims a little, the arms
// fade almost out. Phase 0 must match the starting colours in
// tools/make_space_bmp.py.
#define TWK_CORE0 RGB5(31, 31, 31)
#define TWK_CORE1 RGB5(29, 29, 31)
#define TWK_CORE2 RGB5(26, 27, 31)
#define TWK_CORE3 RGB5(22, 24, 30)
#define TWK_CORE4 RGB5(19, 21, 29)
#define TWK_CORE5 TWK_CORE3
#define TWK_CORE6 TWK_CORE2
#define TWK_CORE7 TWK_CORE1
#define TWK_ARM0  RGB5(24, 25, 31)
#define TWK_ARM1  RGB5(18, 20, 29)
#define TWK_ARM2  RGB5(12, 14, 25)
#define TWK_ARM3  RGB5(7, 9, 20)
#define TWK_ARM4  RGB5(5, 7, 17)
#define TWK_ARM5  TWK_ARM3
#define TWK_ARM6  TWK_ARM2
#define TWK_ARM7  TWK_ARM1
// One row per step, laid out exactly as CGRAM 42..47 (group A, B, C x core,
// arm), with B and C running 3 and 5 phases ahead of A -- so a step is a
// straight copy of one row, no per-colour work.
#define TWK_ROW(a, b, c) TWK_CORE##a, TWK_ARM##a, TWK_CORE##b, TWK_ARM##b, TWK_CORE##c, TWK_ARM##c
#define TWINKLE_ROW_BYTES 12
static const unsigned short twinkleFrames[8 * 6] = {
    TWK_ROW(0, 3, 5), TWK_ROW(1, 4, 6), TWK_ROW(2, 5, 7), TWK_ROW(3, 6, 0),
    TWK_ROW(4, 7, 1), TWK_ROW(5, 0, 2), TWK_ROW(6, 1, 3), TWK_ROW(7, 2, 4)
};

// --- 16-bit xorshift PRNG ---
unsigned short rngState = 0xACE1;
unsigned short rnd(void)
{
    rngState ^= rngState << 7;
    rngState ^= rngState >> 9;
    rngState ^= rngState << 8;
    return rngState;
}

// Point an enemy's OAM slot at the right gfx + palette for its kind. The console
// and the TAC-2 joystick live in separate VRAM/palette slots, so this must run
// whenever a slot's type changes (i.e. on every spawn). Position is set per-frame
// by the draw loop, so park it off-screen here.
void setEnemyAppearance(unsigned char i)
{
    if (enemyType[i] == ENEMY_TANK)
        oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_TANK, PAL_TANK_SP);
    else
        oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_ENEMY, 1);
    oamSetEx(OAM_ENEMY(i), OBJ_LARGE, OBJ_SHOW);
}

// --- Per-frame cost under 816-tcc ---
// The compiler rebuilds a 24-bit pointer for every global array access and
// pads every signed compare with overflow fixups, so the per-enemy loops were
// most of each frame once the board filled up. Those loops -- movement,
// drawing and the collision search -- live in enemies.asm; game logic stays
// here. Box overlap there is one unsigned range check per axis
// (lo < v < hi  <=>  (unsigned)(v - lo - 1) < hi - lo - 1).
//
// While an enemy is still (or again) behind the stats bar it can't hit the
// ship (and the sprite mask keeps it out of sight): normally that's the top
// band (y < PLAYFIELD_TOP); in upside-down mode the bar is at the bottom, so
// it's whichever enemy has its trailing edge still inside the bottom band
// (y + ENEMY_SIZE > PLAYFIELD_BOTTOM).
#define NO_ENEMY 0xFFFF
unsigned short enemyMoveAll(void);      // timers + movement; returns the respawn mask
void enemyDrawAll(void);                // enemy positions -> OAM shadow buffer
unsigned short enemyFindHit(short x, short y, unsigned short span, unsigned short skipHud);
extern unsigned short enemyEscapes;     // set by enemyMoveAll: escaped un-hit this frame
unsigned short ptrBank(const void *p);  // a pointer's bank byte (C can't get at it)

// Move a sprite by writing its X/Y straight into the OAM shadow buffer the
// VBlank ISR uploads. oamSetXY does the same plus maintaining the X bit 8 in
// the high table, but every sprite here keeps 0 <= x <= 255, so that bit never
// changes -- and the library call costs several times as much per sprite.
#define oamMove(id, sx, sy) \
    do { oamMemory[(id)] = (unsigned char)(sx); oamMemory[(id) + 1] = (unsigned char)(sy); } while (0)

// (Re)spawn an enemy at the spawn edge (top normally, bottom in upside-down
// mode) at a random column/speed. Roughly 1 in TANK_CHANCE is a tough TAC-2
// joystick: 3 hits to kill, and it moves more slowly to offset the extra
// effort it takes to destroy.
void spawnEnemy(unsigned char i)
{
    short nx = (short)(rnd() & 0xFF);
    if (nx > SCREEN_W - ENEMY_SIZE) nx -= ENEMY_SIZE;   // keep fully on-screen (0..224)
    enemyX[i]     = nx;
    // Staggered off-screen on the spawn edge: above the screen normally, or
    // below it in upside-down mode (where enemies climb up toward the ship).
    enemyY[i]     = upsideDown ? (short)(224 + (rnd() & 0x7F))
                                : (short)(-ENEMY_SIZE - (rnd() & 0x7F));
    enemyFrac[i]  = 0;
    enemyFlash[i] = 0;
    enemyHurt[i]  = 0;

    if ((rnd() % TANK_CHANCE) == 0)
    {
        enemyType[i]   = ENEMY_TANK;
        enemyHealth[i] = TANK_HEALTH;
        enemySpeed[i]  = 60 + (rnd() & 0x1F);           // ~0.23..0.36 px/frame (heavier)
    }
    else
    {
        enemyType[i]   = ENEMY_NORMAL;
        enemyHealth[i] = 1;
        enemySpeed[i]  = 100 + (rnd() & 0x3F);          // ~0.39..0.64 px/frame
    }
    setEnemyAppearance(i);
}

// Upload the upside-down world's copy of the deep-space map: the same tiles,
// rows in reverse order and each entry's V-flip bit toggled -- an exact mirror
// image. Staged a row at a time through flipRow; it DMAs, so call it while the
// screen is still off.
void buildFlippedDeepMap(void)
{
    unsigned short *row;
    unsigned char r, c;

    for (r = 0; r < DEEP_MAP_ROWS; r++)
    {
        row = &deepspace_map + (DEEP_MAP_ROWS - 1 - r) * 32;
        for (c = 0; c < 32; c++) flipRow[c] = row[c] ^ 0x8000;
        dmaCopyVram((u8 *)flipRow, DEEP_MAP_FLIP_VRAM + r * 32, sizeof(flipRow));
    }
}

// Stats-bar sprite mask: HDMA rewrites window 1's edges (WH0, WH1) each frame
// so the window spans the full width on the bar's scanlines and is empty
// (left > right) everywhere else, and sprites are masked inside it. Enemies
// can then be drawn as they cross the bar and slide out from under it, rather
// than popping in at its edge. Entries are {scanlines, WH0, WH1}, 0 ends the
// table (HDMA counts are at most 127). A sprite at y shows on scanline y + 1,
// so masking scanlines 0..PLAYFIELD_TOP hides exactly its rows with y < 24.
static const unsigned char hudMaskTop[] = {
    PLAYFIELD_TOP + 1, 0, 255,              // scanlines 0..24: masked
    1, 255, 0,                              // the rest: open
    0
};
static const unsigned char hudMaskBottom[] = {
    100, 255, 0,                            // scanlines 0..200: open
    PLAYFIELD_BOTTOM + 1 - 100, 255, 0,
    PLAYFIELD_TOP, 0, 255,                  // 201..224: masked
    0
};

// Point BG2, the backdrop gradient and the stats-bar sprite mask at their
// normal or mirrored versions, to match upsideDown. The gradient's HDMA
// rewrites CGADD on every scanline, which would scatter a CGRAM DMA running at
// the same time -- so only call this once the startup palette uploads are done.
// setModeHdmaColor waits for VBlank and then enables only its own channel, so
// the mask's channel is (re)programmed and enabled after it, still in VBlank.
void setScreenOrientation(void)
{
    const unsigned char *mask;

    if (upsideDown)
    {
        bgSetMapPtr(2, DEEP_MAP_FLIP_VRAM, SC_32x64);
        setModeHdmaColor(SKY_HDMA_CHANNEL, (u8 *)&hdmaGradskygrad_flipList);
        mask = hudMaskBottom;
    }
    else
    {
        bgSetMapPtr(2, DEEP_MAP_VRAM, SC_32x64);
        setModeHdmaColor(SKY_HDMA_CHANNEL, (u8 *)&hdmaGradskygradList);
        mask = hudMaskTop;
    }

    REG_DMAP5   = 0x01;                     // HDMA mode 1: two registers...
    REG_BBAD5   = 0x26;                     // ...WH0 ($2126) and WH1 ($2127)
    REG_A1T5LH  = (unsigned short)mask;
    REG_A1B5    = ptrBank(mask);
    REG_WOBJSEL = 0x02;                     // window 1 applies to sprites
    REG_TMW     = 0x10;                     // mask sprites inside it (main screen)
    REG_HDMAEN  = SKY_HDMA_CHANNEL | HUD_MASK_HDMA_CHANNEL;
}

// Advance the parallax backdrop one frame. Call it once per frame, straight
// after WaitForVBlank: besides the scroll registers it steps the twinkle, which
// writes CGRAM -- only safe during VBlank, so on a frame that doesn't start
// there the step just waits for the next one. Upside-down mode reverses the
// drift so the sky falls "up" too.
void updateBackground(void)
{
    const unsigned char *row;
    unsigned short k;

    if (++twinkleTimer >= TWINKLE_STEP_FRAMES && (REG_HVBJOY & VBL_READY))
    {
        twinkleTimer = 0;
        twinkleOfs += TWINKLE_ROW_BYTES;
        if (twinkleOfs >= sizeof(twinkleFrames)) twinkleOfs = 0;
        // Plain CPU writes rather than a DMA: if this ever ran late, a stray
        // CGRAM write only miscolours one frame, while a DMA colliding with
        // the gradient's HDMA can lock up early (v1) SNES CPUs.
        row = (const unsigned char *)twinkleFrames + twinkleOfs;
        REG_CGADD = TWINKLE_CG;
        for (k = 0; k < TWINKLE_ROW_BYTES; k++) *CGRAM_PALETTE = row[k];
    }

    nearScroll += upsideDown ? NEAR_SCROLL_PX : -NEAR_SCROLL_PX;
    bgSetScroll(1, 0, nearScroll);

    // Deep space crawls at a fraction of a pixel per frame: accumulate
    // 1/256ths and step whole pixels, like the enemies' descent.
    deepFrac += DEEP_SCROLL_SPEED;
    if (deepFrac >= 256)
    {
        deepFrac -= 256;
        deepScroll += upsideDown ? 1 : -1;
        bgSetScroll(2, 0, deepScroll);
    }
}

// Drop a bomb power-up at (sx, sy) -- where a console was just destroyed --
// unless one is already falling. Clamp into the playfield so it stays visible.
void spawnPowerup(short sx, short sy)
{
    if (powerupActive) return;
    if (upsideDown) { if (sy > PLAYFIELD_BOTTOM - POWERUP_SIZE) sy = PLAYFIELD_BOTTOM - POWERUP_SIZE; }
    else            { if (sy < PLAYFIELD_TOP) sy = PLAYFIELD_TOP; }
    powerupX = sx;
    powerupY = sy;
    powerupActive = 1;
}

// Destroy an enemy: start the death animation, score it, and maybe drop a bomb.
// A no-op if it's already dying. Tougher TAC-2 joysticks are worth more points.
// Returns 1 if this call actually killed something, 0 if it was a no-op.
//
// playSound is 0 only for the Y-bomb's mass kill below: the SPC700 sound
// driver's command queue has no overflow protection, and its APU handshake
// waits spin with no timeout -- queuing up to MAX_ENEMIES near-simultaneous
// spcEffect() calls in one frame (e.g. a late-game bomb with a full board)
// can desync it and hang the whole game. The bomb instead plays one
// sfxEnemyHit() for the whole blast.
unsigned char killEnemy(unsigned char i, unsigned char playSound)
{
    if (enemyFlash[i] == 0)
    {
        enemyFlash[i] = FLASH_FRAMES;
        score += (enemyType[i] == ENEMY_TANK) ? TANK_SCORE : SCORE_PER_KILL;
        if (playSound) sfxEnemyHit();

        // Roughly every ~10 kills, drop a bomb power-up where this enemy died.
        if (++killsSinceDrop >= dropThreshold && !powerupActive)
        {
            spawnPowerup(enemyX[i], enemyY[i]);
            killsSinceDrop = 0;
            dropThreshold  = 8 + (rnd() % 5);    // 8..12 kills until the next one
        }
        return 1;
    }
    return 0;
}

// Apply one bullet's worth of damage to an enemy. A normal console dies in one
// hit; the tough TAC-2 joystick soaks up HURT hits (flickering each time) and
// only dies on the blow that drops its health to zero.
void damageEnemy(unsigned char i)
{
    if (enemyFlash[i] > 0) return;               // already dying
    if (enemyHealth[i] > 1)
    {
        enemyHealth[i]--;
        enemyHurt[i] = HURT_FRAMES;              // brief "chipped" flicker
        sfxTankHit();
        return;
    }
    killEnemy(i, 1);
}

// Fire a bullet from the player's top-centre, if a slot is free.
void fireBullet(short px, short py)
{
    unsigned char j;
    for (j = 0; j < NUM_BULLETS; j++)
    {
        if (!bulletActive[j])
        {
            bulletActive[j] = 1;
            bulletX[j] = px + (PLAYER_SIZE / 2) - (BULLET_SIZE / 2);
            // Muzzle sits on whichever edge faces the oncoming enemies.
            bulletY[j] = upsideDown ? (py + PLAYER_SIZE) : (py - BULLET_SIZE);
            return;
        }
    }
}

// Zero-padded decimal into buf, `digits` (1..5) wide plus a NUL. Stands in for
// sprintf: 816-tcc's vsnprintf takes over half a frame per call, so formatting
// the score with it dropped a frame on every kill. Digits come from repeated
// subtraction, since / and % are slow library calls on the 65816 too.
static const unsigned short placeValues[5] = { 10000, 1000, 100, 10, 1 };

void formatDecimal(char *buf, unsigned short value, unsigned short digits)
{
    unsigned short k, place;
    char c;

    for (k = 0; k < digits; k++)
    {
        place = placeValues[5 - digits + k];
        c = '0';
        while (value >= place) { value -= place; c++; }
        buf[k] = c;
    }
    buf[digits] = '\0';
}

// Redraw the score in the stats bar, but only when it actually changed.
void drawScore(void)
{
    if (score == lastScore) return;
    lastScore = score;
    formatDecimal(scoreStr, score, 5);
    consoleDrawText(7, hudRow, scoreStr);
}

// Lose SCORE_PER_KILL points (the value an un-hit kill would have earned), clamped at 0.
void penalizeScore(void)
{
    if (score >= SCORE_PER_KILL) score -= SCORE_PER_KILL;
    else                         score = 0;
}

// Redraw the remaining lives in the stats bar, only when it changed.
void drawLives(void)
{
    if (lives == lastLives) return;
    lastLives = lives;
    formatDecimal(livesStr, lives, 1);                 // START_LIVES is a single digit
    consoleDrawText(19, hudRow, livesStr);
}

// Redraw the bomb count in the stats bar, only when it changed.
void drawBombs(void)
{
    if (bombs == lastBombs) return;
    lastBombs = bombs;
    formatDecimal(bombStr, bombs, 1);                  // capped at MAX_BOMBS = 9
    consoleDrawText(27, hudRow, bombStr);
}

// --- "Game completed" credits crawl -------------------------------------------
// BG0's tilemap is a single wrapping 32x32-tile (256x256px) screen. The block
// is drawn starting at row 1 (the topmost non-clipped row) so the first line
// sits right at the top edge the moment it appears, then continuously nudging
// bgSetScroll down (like the space backdrop's "falling" trick) drifts the whole
// block down the screen and loops it through the blank rows below -- a classic
// scrolling-credits look with no per-frame text redraw needed.
#define NUM_CREDIT_LINES 7
static const unsigned char creditRow[NUM_CREDIT_LINES] = { 1, 3, 6, 8, 10, 12, 15 };
static const unsigned char creditCol[NUM_CREDIT_LINES] = { 4, 4, 11, 9, 5, 3, 7 };
static const char *const creditText[NUM_CREDIT_LINES] = {
    "Thank you for playing.",
    "You completed the game.",
    "Thanks to:",
    "Hampus (coder)",
    "Claude (actuall coder)",
    "Terry (design & testing)",
    "Please play again"
};

void drawCredits(void)
{
    unsigned char k;
    for (k = 0; k < NUM_CREDIT_LINES; k++)
        consoleDrawText(creditCol[k], creditRow[k], (char *)creditText[k]);
}

// Blank each credit line back out (same spot, spaces instead of text) so
// nothing is left behind once the crawl ends and gameplay resumes.
void eraseCredits(void)
{
    unsigned char k, len;
    char blank[26];
    for (k = 0; k < NUM_CREDIT_LINES; k++)
    {
        len = strlen(creditText[k]);
        memset(blank, ' ', len);
        blank[len] = '\0';
        consoleDrawText(creditCol[k], creditRow[k], blank);
    }
}

// Hide every gameplay sprite and both backdrop layers, leaving just the sky
// gradient. Used both when the credits crawl begins and when the player skips
// the whole win sequence early with START.
void clearPlayfield(void)
{
    unsigned char i, j;
    oamSetXY(OAM_PLAYER, 0, OFFSCREEN_Y);
    for (i = 0; i < MAX_ENEMIES; i++) oamSetXY(OAM_ENEMY(i), 0, OFFSCREEN_Y);
    for (j = 0; j < NUM_BULLETS; j++) oamSetXY(OAM_BULLET(j), 0, OFFSCREEN_Y);
    oamSetXY(OAM_POWERUP, 0, OFFSCREEN_Y);
    bgSetDisable(1);
    bgSetDisable(2);
}

// Wipe all round state and drop back into a fresh game -- shared by the
// game-over and game-complete screens' "press START to restart" handling.
void resetGame(short *px, short *py)
{
    unsigned char i, j;
    score = 0;            lastScore = 0xFFFF;  // force HUD redraw
    lives = START_LIVES;  lastLives = 0xFF;
    bombs = START_BOMBS;  lastBombs = 0xFF;
    playerFlash = 0;
    powerupActive = 0;
    killsSinceDrop = 0;   dropThreshold = 10;
    // Mirrored near the top; kept even (like the normal-mode 170) so the -=2
    // per-frame step lands exactly on the y>0 clamp below instead of
    // overshooting to -1, which would wrap the 8-bit sprite Y to the bottom.
    *px = 112; *py = upsideDown ? 32 : 170;
    activeEnemies = START_ENEMIES;              // back to the gentle opening wave
    nextEnemyScore = ENEMIES_PER_LEVEL;         // reset the difficulty ramp
    for (i = 0; i < MAX_ENEMIES; i++)
    {
        enemyType[i]   = ENEMY_NORMAL;
        enemyHealth[i] = 1;
        enemyHurt[i]   = 0;
        if (i < activeEnemies)
            spawnEnemy(i);       // fresh active enemies (sets gfx/palette)
        else
            oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_ENEMY, 1);  // park the rest
    }
    for (j = 0; j < NUM_BULLETS; j++) bulletActive[j] = 0;
}

// Intro splash screen: title + a "START GAME" menu item over the drifting
// space backdrop, with a looping marimba fanfare. Blocks until the player presses
// START, then wipes its text so nothing bleeds into the playfield. Assumes the
// SPC700 is already booted and the backdrop/BG layers are up.
void showTitleScreen(void)
{
    unsigned short down0;
    unsigned char step = 0, frame = 0, note;

    // Keep the player sprite out of sight while the splash is up.
    oamSet(OAM_PLAYER, 0, OFFSCREEN_Y, 3, 0, 0, GFX_PLAYER, 0);

    // Title + menu item, roughly centred on the 32-column screen.
    consoleDrawText(11,  9, "MEGA DRIVER");
    consoleDrawText(12, 11, "INVADERS");
    consoleDrawText( 9, 16, "> START GAME <");
    consoleDrawText(10, 20, "PRESS START");

    while (1)
    {
        // Let the space backdrop keep drifting under the title.
        updateBackground();

        down0 = padsDown(0);

        // Step the fanfare: one note (or rest) every JINGLE_STEP_FRAMES, looping.
        if (frame == 0)
        {
            note = jingleNotes[step];
            if (note) spcEffect(note, SFX_COWBELL, 15 * 16 + PAN_CENTER);
            if (++step >= JINGLE_LEN) step = 0;
        }
        if (++frame >= JINGLE_STEP_FRAMES) frame = 0;

        if (down0 & KEY_START) break;

        spcProcess();
        WaitForVBlank();
    }

    // Wipe the splash text (overwrite each line with matching-length blanks).
    consoleDrawText(11,  9, "           ");
    consoleDrawText(12, 11, "        ");
    consoleDrawText( 9, 16, "              ");
    consoleDrawText(10, 20, "           ");
}

int main(void)
{
    unsigned short pad0, down0;
    unsigned short i, j;        // 16-bit: 816-tcc handles bytes with costly mode switches
    short x = 112, y = 170;     // player position (starts near the bottom)
    short by;                   // a bullet's new y, kept in a local (see 816-tcc note)
    unsigned short respawn;     // enemyMoveAll's respawn mask

    // --- Sound engine: boot the SPC700 and load our effect samples ---
    spcBoot();
    spcSetBank(&SOUNDBANK__);
    // Reserve SPC RAM for BRR sound effects (gunshot is ~12 256-byte blocks);
    // do this before loading any sounds, as in the PVSnesLib likemario sample.
    spcAllocateSoundRegion(STREAM_REGION_PAGES);
    spcStop();
    spcLoad(MOD_SFX);                              // effects bank (soundbank module 0)
    for (i = 0; i < NUM_SFX; i++) spcLoadEffect(i);
    // Register the gunshot BRR sample (vol 15, centre pan, pitch 4) as sound 0.
    spcSetSoundEntry(15, PAN_CENTER, 4,
                     (u16)(&gunshot_brrend - &gunshot_brr), &gunshot_brr, &gunSound);

    // --- Text console (uses the bundled pvsneslib font) ---
    consoleSetTextMapPtr(0x6800);
    consoleSetTextGfxPtr(0x3000);
    consoleSetTextOffset(0x0100);
    consoleInitText(0, 16 * 2, &tilfont, &palfont);

    bgSetGfxPtr(0, 0x2000);
    bgSetMapPtr(0, 0x6800, SC_32x32);
    setMode(BG_MODE1, 0);

    // Night-sky backdrop until the HDMA gradient takes over (setScreenOrientation).
    setPaletteColor(0, SKY_COLOR);

    // --- Parallax space backdrop (loaded once, then only scrolled) ---
    // The .pal files are laid out from CGRAM 0, so copy just each layer's slice.
    dmaCopyVram(&nearstars_til, NEAR_GFX_VRAM, (&nearstars_tilend - &nearstars_til));
    dmaCopyVram((u8 *)&nearstars_map, NEAR_MAP_VRAM, (&nearstars_mapend - &nearstars_map) * 2);
    dmaCopyCGram(&nearstars_pal + NEAR_CG * 2, NEAR_CG, 16 * 2);
    dmaCopyVram(&deepspace_til, DEEP_GFX_VRAM, (&deepspace_tilend - &deepspace_til));
    dmaCopyVram((u8 *)&deepspace_map, DEEP_MAP_VRAM, (&deepspace_mapend - &deepspace_map) * 2);
    dmaCopyCGram(&deepspace_pal + DEEP_CG * 2, DEEP_CG, (32 - DEEP_CG) * 2);
    buildFlippedDeepMap();
    bgSetGfxPtr(1, NEAR_GFX_VRAM);
    bgSetMapPtr(1, NEAR_MAP_VRAM, SC_32x64);
    bgSetGfxPtr(2, DEEP_GFX_VRAM);
    bgSetMapPtr(2, DEEP_MAP_VRAM, SC_32x64);
    bgSetEnable(1);
    bgSetEnable(2);

    // --- Stats bar: top 3 rows (y 0..23), kept clear of gameplay ---
    // Row 0 lands in the overscan ZSNES crops, so the HUD sits on row 1 (the
    // topmost fully-visible row).
    consoleDrawText(1, hudRow, "SCORE");
    consoleDrawText(13, hudRow, "LIVES");
    consoleDrawText(21, hudRow, "BOMBS");
    drawScore();
    drawLives();
    drawBombs();

    // --- Player gfx -> VRAM 0x0000, palette slot 0. Sizes: small 8, large 32. ---
    oamInitGfxSet(&sprites_til, (&sprites_tilend - &sprites_til),
                  &sprites_pal, (&sprites_palend - &sprites_pal),
                  0, VRAM_PLAYER, OBJ_SIZE8_L32);

    // --- Enemy + bullet gfx/palettes (loaded while the screen is still off) ---
    dmaCopyVram(&enemy_til,  VRAM_ENEMY,  (&enemy_tilend  - &enemy_til));
    dmaCopyVram(&bullet_til, VRAM_BULLET, (&bullet_tilend - &bullet_til));
    dmaCopyVram(&powerup_til, VRAM_POWERUP, (&powerup_tilend - &powerup_til));
    dmaCopyVram(&tac2_til,   VRAM_TANK,   (&tac2_tilend   - &tac2_til));
    dmaCopyCGram(&enemy_pal,  PAL_ENEMY_CG,  (&enemy_palend  - &enemy_pal));
    dmaCopyCGram(&bullet_pal, PAL_BULLET_CG, (&bullet_palend - &bullet_pal));
    dmaCopyCGram(&powerup_pal, PAL_POWERUP_CG, (&powerup_palend - &powerup_pal));
    dmaCopyCGram(&tac2_pal,   PAL_TANK_CG,   (&tac2_palend   - &tac2_pal));

    // Player: sprite 0, priority 3 (in front), large (32x32), palette 0
    oamSet(OAM_PLAYER, x, y, 3, 0, 0, GFX_PLAYER, 0);
    oamSetEx(OAM_PLAYER, OBJ_LARGE, OBJ_SHOW);

    // Enemies: large (32x32), palette 1. Reserve all MAX_ENEMIES OAM slots (parked
    // off-screen) so the dormant ones stay hidden until the score ramp activates
    // them; only the START_ENEMIES active ones get a starting position.
    for (i = 0; i < MAX_ENEMIES; i++)
    {
        enemyType[i]   = ENEMY_NORMAL;
        enemyHealth[i] = 1;
        enemyHurt[i]   = 0;
        if (i < activeEnemies)
            spawnEnemy(i);                 // sets position + the right gfx/palette
        else
        {
            oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_ENEMY, 1);
            oamSetEx(OAM_ENEMY(i), OBJ_LARGE, OBJ_SHOW);
        }
    }

    // Bullets: small (8x8), palette 2, parked off-screen until fired
    for (j = 0; j < NUM_BULLETS; j++)
    {
        bulletActive[j] = 0;
        oamSet(OAM_BULLET(j), 0, OFFSCREEN_Y, 2, 0, 0, GFX_BULLET, 2);
        oamSetEx(OAM_BULLET(j), OBJ_SMALL, OBJ_SHOW);
    }

    // Bomb power-up: large (32x32), palette 3, parked off-screen until dropped
    oamSet(OAM_POWERUP, 0, OFFSCREEN_Y, 2, 0, 0, GFX_POWERUP, 3);
    oamSetEx(OAM_POWERUP, OBJ_LARGE, OBJ_SHOW);

    setScreenOn();

    // Sky gradient + stats-bar sprite mask via HDMA -- only now that every
    // CGRAM upload is done.
    setScreenOrientation();

    // Intro splash: title + "START GAME" menu, with a fanfare. Returns once the
    // player presses START, dropping straight into the action below.
    showTitleScreen();

    while (1)
    {
        // --- Space backdrop: scroll both layers a notch and step the twinkle.
        //     First thing after VBlank, so it stays tear-free (and the twinkle's
        //     CGRAM writes land in time), and before the game-over check so the
        //     sky keeps drifting while frozen. ---
        updateBackground();

        pad0  = padsCurrent(0);
        down0 = padsDown(0);

        // Out of lives: freeze the field (sprites hold their last positions)
        // until START is pressed, then wipe state and drop back into the action.
        if (gameOver)
        {
            if (down0 & KEY_START)
            {
                consoleDrawText(11, 13, "         ");       // erase "GAME OVER"
                consoleDrawText(10, 15, "           ");     // erase "PRESS START"
                resetGame(&x, &y);
                gameOver = 0;
            }
            spcProcess();
            WaitForVBlank();
            continue;
        }

        // Score hit WIN_SCORE: a short freeze, a "CONGRATULATIONS" banner, then
        // the screen clears and the credits crawl until START is pressed.
        if (gameWon)
        {
            if (down0 & KEY_START)
            {
                // START can arrive as little as one frame after the winning
                // shot was fired, so its gunshot sample may still be streaming
                // to the SPC700 -- and the reload below must not touch the APU
                // ports until it's done (see STREAM_SETTLE_FRAMES). Feed the
                // stream to completion first.
                for (i = 0; i < STREAM_SETTLE_FRAMES; i++)
                {
                    spcProcess();
                    WaitForVBlank();
                }

                // Blank the HUD at its *current* row before flipping it. Normally
                // the WIN_PHASE_CONGRATS->CREDITS transition below already does
                // this, but START is checked first in this whole gameWon block,
                // so pressing it early (during WIN_PHASE_PAUSE/CONGRATS) skips
                // that transition entirely -- without this, the old row's
                // labels+values are left behind, sitting inside the live
                // playfield once the stats bar flips to the opposite edge (the
                // "scoreboard renders wrong in upside-down mode" symptom).
                consoleDrawText(1, hudRow, "     ");
                consoleDrawText(7, hudRow, "     ");
                consoleDrawText(13, hudRow, "     ");
                consoleDrawText(19, hudRow, " ");
                consoleDrawText(21, hudRow, "     ");
                consoleDrawText(27, hudRow, " ");
                clearPlayfield();                           // hide any still-visible sprites too

                // Flip into (or back out of) the mirrored upside-down world:
                // ship near the top, enemies climbing from the bottom, and
                // the stats bar flipped to match -- see the upsideDown/hudRow
                // comment near their declarations.
                upsideDown = !upsideDown;
                hudRow = upsideDown ? HUD_ROW_BOTTOM : HUD_ROW_TOP;

                // Mirror deep space and the sky gradient with everything else,
                // reflecting the scroll offset too so the planets on screen
                // flip in place rather than jumping elsewhere in the loop.
                deepScroll = (DEEP_MAP_ROWS * 8 - 224) - deepScroll;
                bgSetScroll(2, 0, deepScroll);
                setScreenOrientation();

                // Skip straight to a fresh round. Both erases are safe no-ops
                // if that particular screen was never drawn in the first place.
                consoleDrawText(8, 12, "               ");  // erase "CONGRATULATIONS"
                eraseCredits();
                creditsScroll = 0;
                bgSetScroll(0, 0, 0);                       // BG0 back to its normal HUD position
                consoleDrawText(1, hudRow, "SCORE");        // HUD labels were hidden for the crawl
                consoleDrawText(13, hudRow, "LIVES");
                consoleDrawText(21, hudRow, "BOMBS");
                bgSetEnable(1);                             // bring the space backdrop back
                bgSetEnable(2);
                // Loading a module wipes SPC RAM, so switch back to the effects
                // bank and re-register everything exactly as at startup: the
                // stream-region reservation (whose driver command also stops the
                // module and re-initialises the driver's streaming state -- a
                // clean slate for the gunshot streams the next round will fire),
                // then the effect instruments, then the raw gunshot BRR sample.
                spcStop();
                spcAllocateSoundRegion(STREAM_REGION_PAGES);
                spcLoad(MOD_SFX);
                for (i = 0; i < NUM_SFX; i++) spcLoadEffect(i);
                spcSetSoundEntry(15, PAN_CENTER, 4,
                                 (u16)(&gunshot_brrend - &gunshot_brr), &gunshot_brr, &gunSound);
                resetGame(&x, &y);
                gameWon = 0;
            }
            else if (winPhase == WIN_PHASE_PAUSE)
            {
                // Brief freeze on the finishing frame before the banner appears.
                if (winTimer > 0) winTimer--;
                else
                {
                    consoleDrawText(8, 12, "CONGRATULATIONS");
                    spcStop();
                    spcLoad(MOD_SUMMERGAMES);
                    spcPlay(0);
                    musicFrame = 0;
                    winPhase  = WIN_PHASE_CONGRATS;
                    winTimer  = WIN_CONGRATS_FRAMES;
                }
            }
            else if (winPhase == WIN_PHASE_CONGRATS)
            {
                // Banner stays up over the still-frozen field for ~5 seconds,
                // then the screen clears and the crawl takes over. Keep timing
                // the music through this phase too, so the loop restart (once
                // WIN_PHASE_CREDITS is reached) lands at the right point.
                musicFrame++;
                if (winTimer > 0) winTimer--;
                else
                {
                    consoleDrawText(8, 12, "               ");  // erase "CONGRATULATIONS"
                    consoleDrawText(1, hudRow, "     ");   // hide the HUD so it doesn't scroll
                    consoleDrawText(7, hudRow, "     ");   // with the credits (BG0 is shared)
                    consoleDrawText(13, hudRow, "     ");
                    consoleDrawText(19, hudRow, " ");
                    consoleDrawText(21, hudRow, "     ");
                    consoleDrawText(27, hudRow, " ");
                    clearPlayfield();
                    creditsScroll = 0;
                    creditsPause  = CREDITS_START_DELAY_FRAMES;
                    creditsFrac   = 0;
                    winPhase      = WIN_PHASE_CREDITS;
                }
            }
            else  // WIN_PHASE_CREDITS
            {
                // MOD_SUMMERGAMES has no baked-in loop point (see
                // MUSIC_LOOP_FRAMES' comment), so restart it by hand once its
                // known length has played out.
                if (++musicFrame >= MUSIC_LOOP_FRAMES)
                {
                    musicFrame = 0;
                    spcPlay(0);
                }

                // Blank pause first, then the crawl text is drawn once and
                // starts drifting down. A sub-pixel accumulator (see
                // CREDITS_SCROLL_SPEED) paces the 1px steps evenly.
                if (creditsPause > 0)
                {
                    creditsPause--;
                    if (creditsPause == 0) drawCredits();
                }
                else
                {
                    unsigned short acc = creditsFrac + (unsigned short)CREDITS_SCROLL_SPEED;
                    if (acc >> 8)
                    {
                        creditsScroll -= 1;          // drift down, like the backdrop's fall
                        bgSetScroll(0, 0, creditsScroll);
                    }
                    creditsFrac = (unsigned char)(acc & 0xFF);
                }
            }
            spcProcess();
            WaitForVBlank();
            continue;
        }

        if (pad0 & KEY_LEFT  && x > 0)                 x -= 2;
        if (pad0 & KEY_RIGHT && x < SCREEN_W - PLAYER_SIZE) x += 2;   // 256 - 21
        if (upsideDown)
        {
            // Stats bar lives at the bottom here, so the reserved band is the
            // low boundary instead of the high one -- otherwise same as below.
            if (pad0 & KEY_UP    && y > 0)                              y -= 2;
            if (pad0 & KEY_DOWN  && y < PLAYFIELD_BOTTOM - PLAYER_SIZE) y += 2;
        }
        else
        {
            if (pad0 & KEY_UP    && y > PLAYFIELD_TOP)      y -= 2;       // stay below stats bar
            if (pad0 & KEY_DOWN  && y < 224 - PLAYER_SIZE)  y += 2;       // 224 - 21
        }

        if (down0 & (KEY_A | KEY_B)) { fireBullet(x, y); sfxFire(); }

        // Y = screen-clearing bomb: spend one from inventory to detonate every
        // console at once. Does nothing when the player is out of bombs.
        if ((down0 & KEY_Y) && bombs > 0)
        {
            // One detonation cue for the whole blast, not one per enemy killed
            // (see killEnemy's playSound comment) -- avoids flooding the SPC700
            // command queue when a bomb goes off with a full board of enemies.
            unsigned char killedAny = 0;
            bombs--;
            for (i = 0; i < activeEnemies; i++) killedAny |= killEnemy(i, 0);  // a bomb flattens even tanks
            if (killedAny) sfxEnemyHit();
        }

        // Draw the player; while flashing (recently hit) blink on/off every 4 frames.
        // Per-frame updates use oamSetXY (position only) -- the attributes were set
        // once at init, so there's no need to rewrite them every frame.
        if (playerFlash > 0) playerFlash--;
        if (playerFlash > 0 && ((playerFlash >> 2) & 1))
            oamMove(OAM_PLAYER, 0, OFFSCREEN_Y);
        else
            oamMove(OAM_PLAYER, x, y);

        // --- Move bullets toward the enemies; deactivate once they leave the
        //     stats-bar edge (top normally, bottom in upside-down mode) ---
        for (j = 0; j < NUM_BULLETS; j++)
        {
            if (bulletActive[j])
            {
                by = bulletY[j] + (upsideDown ? BULLET_SPEED : -BULLET_SPEED);
                bulletY[j] = by;
                if (upsideDown ? (by >= PLAYFIELD_BOTTOM) : (by < PLAYFIELD_TOP))
                    bulletActive[j] = 0;   // stop at the stats bar
            }
        }

        // --- Difficulty ramp: the more the score climbs, the more consoles are in
        //     play at once -- one extra each time the score passes the next
        //     ENEMIES_PER_LEVEL threshold, capped at MAX_ENEMIES. A slow, steady
        //     build, never a sudden swarm. Each newly activated enemy drops in from
        //     the top like a normal spawn. The while handles a bomb that crosses
        //     several thresholds in one frame. ---
        while (activeEnemies < MAX_ENEMIES && score >= nextEnemyScore)
        {
            spawnEnemy(activeEnemies++);
            nextEnemyScore += ENEMIES_PER_LEVEL;
        }

        // --- Update enemies (enemyMoveAll, enemies.asm): flicker/blink timers
        //     tick, dying ones hold still, the rest move toward the ship
        //     (descend normally, ascend in upside-down mode). Enemies that
        //     finished dying or escaped un-hit come back as a bit mask and are
        //     respawned here in index order, so the RNG sequence is unchanged. ---
        respawn = enemyMoveAll();
        for (i = 0; i < enemyEscapes; i++) penalizeScore();   // escaped un-hit
        for (i = 0; respawn; i++, respawn >>= 1)
            if (respawn & 1) spawnEnemy(i);

        // --- Collisions: bullet (8x8) vs enemy (32x32). Each live bullet takes
        //     out the first enemy it overlaps (enemyFindHit, enemies.asm). ---
        for (j = 0; j < NUM_BULLETS; j++)
        {
            if (!bulletActive[j]) continue;
            i = enemyFindHit(bulletX[j] + (BULLET_SIZE - 1), bulletY[j] + (BULLET_SIZE - 1),
                             ENEMY_SIZE + BULLET_SIZE - 1, 0);
            if (i == NO_ENEMY) continue;
            bulletActive[j] = 0;   // bullet spent
            damageEnemy(i);        // chip a tank, or destroy a console
        }

        // --- Win check: score crossed WIN_SCORE (from a bullet kill above, or
        //     the Y-bomb earlier this frame). The field stays visible, frozen,
        //     for a short beat -- the win sequence's own state machine (see the
        //     gameWon block above the movement code) handles the banner, the
        //     screen clear, and the credits crawl from here. ---
        if (!gameWon && score >= WIN_SCORE)
        {
            gameWon  = 1;
            winPhase = WIN_PHASE_PAUSE;
            winTimer = WIN_PAUSE_FRAMES;
            sfxPowerup();                      // bright fanfare for winning
        }

        // --- Collisions: player (21x21) vs enemy. Costs a life + flash; brief i-frames ---
        // Skipped once gameWon just triggered above -- winning ends the round outright,
        // so a same-frame hit can't also set gameOver and leave the two states tangled.
        if (playerFlash == 0 && !gameWon)
        {
            // Ignores enemies still behind the stats bar (skipHud = 1).
            i = enemyFindHit(x + (PLAYER_SIZE - 1), y + (PLAYER_SIZE - 1),
                             ENEMY_SIZE + PLAYER_SIZE - 1, 1);
            if (i != NO_ENEMY)
            {
                if (lives > 0) lives--;
                spawnEnemy(i);                         // the console that hit us is gone (no score)
                if (lives == 0)
                {
                    gameOver = 1;
                    consoleDrawText(11, 13, "GAME OVER");
                    consoleDrawText(10, 15, "PRESS START");
                    sfxGameOver();                     // mournful strings
                }
                else
                {
                    playerFlash = PLAYER_FLASH_FRAMES; // blink + invulnerable for a moment
                    sfxCollide();                      // took a hit
                }
            }
        }

        // --- Bomb power-up: drift toward the ship, get caught, or drift off-screen ---
        if (powerupActive)
        {
            powerupY += upsideDown ? -POWERUP_SPEED : POWERUP_SPEED;
            if (upsideDown ? (powerupY <= -POWERUP_SIZE) : (powerupY >= 224))
                powerupActive = 0;                         // missed -- drifted off-screen
            else if (x + PLAYER_SIZE > powerupX &&
                     x < powerupX + POWERUP_SIZE &&
                     y + PLAYER_SIZE > powerupY &&
                     y < powerupY + POWERUP_SIZE)
            {
                powerupActive = 0;
                if (bombs < MAX_BOMBS) bombs++;            // collected: stock a bomb
                sfxPowerup();
            }
        }

        // --- Draw enemies (enemyDrawAll, enemies.asm), blinking while dying or
        //     chipped. The stats-bar sprite mask clips them on the bar's
        //     scanlines, so they slide out from under it. ---
        enemyDrawAll();

        // --- Draw bullets ---
        for (j = 0; j < NUM_BULLETS; j++)
        {
            if (bulletActive[j])
                oamMove(OAM_BULLET(j), bulletX[j], bulletY[j]);
            else
                oamMove(OAM_BULLET(j), 0, OFFSCREEN_Y);
        }

        // --- Draw the bomb power-up ---
        if (powerupActive)
            oamMove(OAM_POWERUP, powerupX, powerupY);
        else
            oamMove(OAM_POWERUP, 0, OFFSCREEN_Y);

        drawScore();
        drawLives();
        drawBombs();

        spcProcess();        // feed queued sound messages to the SPC700 each frame
        WaitForVBlank();
    }
    return 0;
}
